### ISSUE TITLE
It is not possible to disable preview on folder share with pydio 6.3.1

### ISSUE THREAD

**Issue by Ellega** [pydio/pydio-core#1079]
When you disable preview. It come back enable after you save the setting.

![2016-03-14_103341](https://cloud.githubusercontent.com/assets/3939543/13740335/7c4264a4-e9d0-11e5-9b99-da833de5333e.png)

**Comment by cdujeu** [comment]
@Ellega is it the case with all types of files?

**Comment by Ellega** [comment]
Indeed no. 

after a quick test

works fine  : doc, docx, xls, xlsx

bug  with : pdf , zip

**Comment by cdujeu** [comment]
it's an expected behavior: we don't have a "download-only" mode for folders (we wouldn't really know how to display that). We should however make this checkbox checked and readonly to reflect that.
We were thinking as well of hiding the "download limit" field if you don't check the "Download" permission, what do you think?

**Comment by Ellega** [comment]
All of this goes in a good way for the user experience :)
