### ISSUE TITLE
[rest.php] Missing response information for mkdir and delete 

### ISSUE THREAD

**Issue by tolgadevsec** [pydio/pydio-core#715]
I used the REST API this time (with Postman as REST Client) but the results are the same for the  CLI-Interface:

mkdir
URL: http://myserver.com/api/<repositoryid>/mkdir
POST-Parameter:
“dir” => “/”
“dirname” => “/Testdir”

– No Success-Message although the directories will get created (but I’ll get at least an
   Error-Message, if the directory already exists)

delete (for files or directories)
URL: http://myserver.com/api/<repositoryid>/delete
POST-Parameter:
“nodes[]” => “/Testdir”

– I neither get a Success-Message nor an Error-Message in my response (but it does delete
   a file or a directory)
– No Error-Message if I try to delete a non-existing directory or file
– I’m getting an Error-Message if I write “nodes” without the square brackets and it
   says that “I’m not allowed to delete the entire directory structure” (I’m using
   the REST API with my administrator profile)
   You should add the square brackets to your API documentation if those are really
   necessary to use your API correctly.

**Comment by tolgauen** [comment]
That depends.. how am I now supposed to delete multiple files? I tried it with the following:
"file" => /test123
"file" => /test213
This doesnt work, the second parameter will be considered but the first will not. I thought that it would work the same way like in the web ui, but the web ui is using the "nodes[]" key instead of "file". If I use the nodes[]-key then I'll get an error saying that nothing has been selected.
