### ISSUE TITLE
Document CORS configs to be able to use a different domain for shares

### ISSUE THREAD

**Issue by cdujeu** [pydio/pydio-core#767]
The whole-minisite approach makes it complicated to use a different domain or subdomains for share folder. We should modify the client JS code and publish necessary CORS headers to make it work.

**Comment by max-k** [comment]
I'm trying to enable CORS in nginx to host Pydio's public links on a different domain.
Without success yet, but if it works, I'll post the results of my investigations here.

**Comment by max-k** [comment]
Almost done but there is one more query impossible to allow and I don't know why :
**Here is the query:**
Host: host1
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Access-Control-Request-Method: GET
Access-Control-Request-Headers: x-prototype-version,x-requested-with
Origin: host2
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
**Here is the response:**
Access-Control-Allow-Credentials: true
Connection: keep-alive
Content-Length: 173
Content-Type: text/html
Date: Wed, 24 Feb 2016 15:14:24 GMT
Keep-Alive: timeout=60
Server: nginx/1.9.10
X-Frame-Options: ALLOW FROM https://host2
access-control-allow-headers: DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,X-Prototype-Version,X-Json
access-control-allow-methods: GET, POST, PUT, DELETE, OPTIONS
access-control-allow-origin: https://host2
access-control-expose-headers: DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,X-Prototype-Version,X-Json
**Here is the result:**
405 Not Allowed

**Comment by max-k** [comment]
**Here is my nginx CORS related configuration :**
```
map $host $origin {
  host1 https://host2;
  host2 https://host1;
}
server {
  server_name host1 host2;
[...]
  location / {
  more_clear_headers 'X-Frame-Options';
  more_set_headers "X-Frame-Options: SAMEORIGIN";
  more_clear_headers 'Access-Control-Allow-Origin';
  more_set_headers "Access-Control-Allow-Origin: $origin";
  more_set_headers 'Access-Control-Allow-Credentials: true';
  more_set_headers 'Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS';
  more_set_headers 'Access-Control-Allow-Headers: DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,X-Prototype-Version,X-Json';
  more_set_headers 'Access-Control-Expose-Headers: DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,X-Prototype-Version,X-Json';

  if ($request_method ~ 'OPTIONS') {
    add_header Access-Control-Max-Age 1728000;
    add_header Content-Type 'text/plain charset=UTF-8';
    add_header Content-Length 0;
    return 204;
  }
}
[...]
}
```

**Comment by max-k** [comment]
Same result with :
more_set_headers "X-Frame-Options: ALLOW FROM $origin";
