### ISSUE TITLE
Pydio Etherpad plugins : multiple access and connexion lost

### ISSUE THREAD

**Issue by HubertChomette** [pydio/pydio-core#867]
Hi there,
As I understand, If I open a file with collaborative tools (etherpad), It connect to a new or existing pad and past the file data.
Suppose we have a workspace with a file SHARE.TXT. Differents persons access to the file using Etherpad (right click, open with collaborative tools).
If someone is disconnected or connect later, it will reformat the last version of the pad with the file data.
If we use Timeslider to restore, the only solution is to cut/paste.
Maybe the solution will to detect if there is activity on the pad before past the file data.

**Comment by cdujeu** [comment]
Hi Hubert
I don't really understand that one. 
Do you hit "Save" sometimes when collaborating ? Do you mean there should be an auto-save maybe?
-c

**Comment by HubertChomette** [comment]
If I open a file with etherpad, it connect to the pad and synchronise the contain of the file to the pad.
If I use a document on a shared directory.
First person open it with etherpad, the pad is synchrone with the file contain.
This person made some change without saving it.
Suppose now that a second person try to connect to the pad. He right click to the file , open with etherpad. This automatically synchronise the pad with the version of the file.
The first person changement disappears and the solution is to use the timeslider to refind his last version.

I think that the solution is to synchronise the file contains with the pad only If nobody is connected to the pad or auto-save (with a short interval).

**Comment by cdujeu** [comment]
Ok, currently having a second look at the code, here are a couple of ideas (linked to this bug but not only, to your other ones too).
Let's consider two different cases: pads linked to a file ( = collaborative edition ) and "free" pads opened just for a discussion. These would have different lifecycles.
#### File Pads
##### Naming
Instead of naming the PadID based on the filename, let's generated a unique ID, stored inside the pydio file metadata, with a global scope. This has the advantage to make this Pad ID accessible by any user accessing the file, including shared users inside shared folders!
##### Lifecycle
 * Opening a collaborative file: 
   * if it's not already opened, load file content into pad. Problem if a previous pad was not correctly shutdown? Can this happen
   * If it's already open, just connect to the associated pad
 * During pad usage
   * Monitor pad changes to display a "*" in the tab, to indicate the current content needs saving. Let users save when they want.
 * Pad closing
   * Check if no more authors are connected and DELETE the pad.

#### Open Pads
 * Idea: instead of adding the menu in the user menu, handle a new .pad filetype, that would be recognized as a simple pointer to pad ID. The file contains just the Pad ID (not the content, the pad content is kept on the etherpad-side), and can have a nice icon. 
 * For example, anyone could create inside a folder a "Discussion About This Topic.pad", and use it as a base for opening an associated pad.
 * Only when the file is deleted, the pad is DELETED on the etherpad side.

@HubertChomette any comments / ideas / insights about this spec?

**Comment by HubertChomette** [comment]
it seem's to be a good strategy.
The DELETED action is a very good idea, (even mandatory) for security
reasons.
The user menu doesn't have a real sens and expose all pad to all users.


2015-03-18 19:52 GMT+01:00 Charles du Jeu <notifications@github.com>:
