### ISSUE TITLE
access.smb based on PHP wrapper for smbclient and libsmbclient-php

### ISSUE THREAD

**Issue by mwehr** [pydio/pydio-core#929]
Hi,

I did a rewrite of the existing access.smb module. 
The modified version uses a wrapper lib which can use the libsmbclient-php or the smbclient for working with SMB/CIF shares.
Benefits of libsmbclient-php are:
 * No need for temp files.
 * More secure, smbclient user/pass can been seen with 'ps -ef'
 * Should be more efficent

If there is any interest I could do a clone and add my module ?

regards

Mario

**Comment by cdujeu** [comment]
Hi Mario, 
You can definitely submit a PR with your changes, we'll have a look at it. but it will probably take some time as many users are using access.smb, and we'll have to make sure that every possible cases is working.
However, regarding the password seen with ps -ef, we already have an option to pass it via ENV variable instead of command line.
Finally, if you submit a PR, don't forget to sign the CLA (see Contribute page on the web site).
-c

**Comment by cdujeu** [comment]
To be submitted as PR, closing for now.

**Comment by cdujeu** [comment]
@mwehr, i don't think you did ever submit a PR with this code, can you do that?

**Comment by mwehr** [comment]
Done :-)
